[project]
name = "pl-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "lightning>=2.6.0",
    "torchvision>=0.24.1",
]
